version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX.
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo "Building the static site..."
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Congiguring NGINX

artifacts:
  files:
    - /var/www/html/index.html
